version: '3.9'

services:
  nestapp:
    container_name: users
    image: users:1.0.0
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_USERNAME=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=JS_users
      - PG_PORT=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=JS_users
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}